import Head from 'next/head'
import { useState } from 'react'

export default function Home() {

	//Declara uma variável dados com state e atribui objeto
	const [data, setData] = useState({
		name: '',
		email: ''
	});

	//Recebe os dados dos capos do formulário
	const valueInput = (evnt) => setData({ ...data, [evnt.target.name]: evnt.target.value});

	//Executa a função quando o botão salvar do form for pressionado
	const addUser = (evnt) => {

		//Bloqueia o auto refresh
		evnt.preventDefault();

		console.log("Enviado para a API");
		console.log("Nome enviado: " + data.name);
		console.log("Email enviado: " + data.email);
	}

	return (
		<>

			<Head>
				<title>React CRUD</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous"></link>
				<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
			</Head>

			<main>
				<div className="container">
					<div className="row">
						<h2>Cadastrar Usuário</h2>
					</div>
					<form onSubmit={addUser}>
						<div className="mb-3">
							<label htmlFor="user_name" className="form-label">Nome</label>
							<input type="text" className="form-control" id="user_name" value={data.name} onChange={valueInput} name='name' placeholder='Insira o nome do usuário...'/>
						</div>
						<div className="mb-3">
							<label htmlFor="user_email" className="form-label">Email</label>
							<input type="email" className="form-control" id="user_email" value={data.email} onChange={valueInput} name='email' placeholder='Insira o email do usuário...'/>
						</div>
						<button type="submit" className="btn btn-dark">Salvar</button>
					</form>
				</div>
			</main>
		</>
	)
}